let language = {
    english: {
        promotionsText: "Promotions",
        winterText: "Winter Offer",
        springText: "Spring Offer",
        autumnText: "Autumn Offer",
        filterByNamePlaceholder: "Filter by name",
        filterByPricePlaceholder: "Price",
        totalPriceText: "Total Price: ",
        text: "Language:",
        shortDescriptionText: "Short Description: ",
        nameText:"Name: ",
        categoryText: "Category: ",
        descriptionText: "Description: ",
        oldPriceText: "Old Price: ",
        newPriceText: "New Price: ",
        headertext2: "The rest of the products",
        filterPlaceHolder: "Product name",
        resetFiltersButton: "Reset al filters",
        totalBoughtItems: "Total Bought Items",
        promoMessageHeader: "Don't miss today's hot deal !",
        couponPlaceHolder: "Coupon...",
        couponButton: "Apply coupon",
        invalidCoupon: "Invalid coupon",
        addCartButton: "Add to cart",
        removeCartButton: "Remove from cart",
        footerHeader: "We bring you only the best products that can be randomly generated!",
        footerDisclaimer: "Content from faker.js with images from Lorem Picsum"
    },
    espagnol: {
        promotionsText: "Promociones",
        winterText: "Oferta Invierno",
        springText: "Oferta Primavera",
        autumnText: "Oferta Otoño",
        filterByNamePlaceholder: "Filtrar por nombre",
        filterByPricePlaceholder: "Precio",
        totalPriceText: "Precio total: ",
        text: "Idioma:",
        shortDescriptionText: "Breve descripción: ",
        nameText:"Nombre: ",
        categoryText: "Categoría: ",
        descriptionText: "Descripción: ",
        oldPriceText: "Precio anterior: ",
        newPriceText: "Nuevo precio: ",
        headertext2: "El resto de productos",
        filterPlaceHolder: "Nombre del producto",
        resetFiltersButton: "Restablecer filtros",
        totalBoughtItems: "Total de artículos comprados",
        promoMessageHeader: "¡No te pierdas la gran oferta de hoy!",
        couponPlaceHolder: "Cupón...",
        couponButton: "Aplicar cupón",
        invalidCoupon: "Cupón no válido",
        addCartButton: "Añadir a la cesta",
        removeCartButton: "Quitar del carrito",
        footerHeader: "¡Te traemos solo los mejores productos que se pueden generar aleatoriamente!",
        footerDisclaimer: "Contenido de faker.js con imágenes de Lorem Picsum."
    },
    francais: {
        promotionsText: "Promotions",
        winterText: "Offre d'hiver",
        springText: "Offre de printemps",
        autumnText: "Offre d'automne",
        filterByNamePlaceholder: "Filtrer par nom",
        filterByPricePlaceholder: "Prix",
        totalPriceText: "Prix total: ",
        text: "Langue:",
        shortDescriptionText: "Brève Description: ",
        nameText:"Nom: ",
        categoryText: "Catégorie: ",
        descriptionText: "La description: ",
        oldPriceText: "Ancien prix: ",
        newPriceText: "Nouveau prix: ",
        headertext2: "Le reste des produits",
        filterPlaceHolder: "Nom du produit",
        resetFiltersButton: "Réinitialiser les filtres",
        totalBoughtItems: "Total des articles achetés",
        promoMessageHeader: "Ne manquez pas l'offre d'aujourd'hui !",
        couponPlaceHolder: "Coupon...",
        couponButton: "Appliquer Coupon",
        invalidCoupon: "Coupon invalide",
        addCartButton: "Ajouter au panier",
        removeCartButton: "Retirer du panier",
        footerHeader: "Nous ne vous apportons que les meilleurs produits qui peuvent être générés aléatoirement !",
        footerDisclaimer: "Contenu de faker.js avec des images de Lorem Picsum."
    },
    romanian: {
        promotionsText: "Promoții",
        winterText: "Oferta de iarna",
        springText: "Oferta de primavara",
        autumnText: "Oferta de toamna",
        filterByNamePlaceholder: "Filtrare dupa nume",
        filterByPricePlaceholder: "Pret",
        totalPriceText: "Pretul Total: ",
        text: "Limba:",
        shortDescriptionText: "Scurta Descriere: ",
        nameText:"Nume: ",
        categoryText: "Categorie: ",
        descriptionText: "Descriere: ",
        oldPriceText: "Pret vechi: ",
        newPriceText: "Pret nou: ",
        headertext1: "Produsul aleatoriu al zilei",
        headertext2: "Restul produselor",
        filterPlaceHolder: "Nume produs",
        resetFiltersButton: "Reseteaza toate filtrele",
        totalBoughtItems: "Numar total produse cumparate",
        promoMessageHeader: "Oferta zile de azi !",
        couponPlaceHolder: "Cod...",
        couponButton: "Aplicati cupon",
        invalidCoupon: "Cupon invalid",
        addCartButton: "Adauga in cos",
        removeCartButton: "Scoate din cos",
        footerHeader: "Va aducem cele mai bune produse generate aleator!",
        footerDisclaimer: "Continut generat cu faker.js si imagini din Lorem Picsum."
    }
}

export default language;
